#include <esp_wifi.h>

#define ESP_WIFI_SSID      CONF_ESP_WIFI_SSID
#define ESP_WIFI_PASS      CONF_ESP_WIFI_PASS
#define ESP_MAXIMUM_RETRY  CONF_ESP_MAXIMUM_RETRY
#define ESP_WIFI_SCAN_AUTH_MODE_THRESHOLD WIFI_AUTH_WPA2_PSK
#define EXAMPLE_H2E_IDENTIFIER ""
#define ESP_WIFI_SAE_MODE WPA3_SAE_PWE_HASH_TO_ELEMENT

#define WIFI_CONNECTED_BIT BIT0
#define WIFI_FAIL_BIT      BIT1

void wifi_init_sta(void);